### ISSUE TITLE
Maven library for AWS pre-built provider

### ISSUE THREAD

**Issue by mirsilstan** [hashicorp/cdktf-provider-aws#438]
Hi,

The current listed build targets of the AWS pre-built provider are: npm, Pypi, Nuget, Maven.
I can find the npm package for Typescript and the Pypi package for Python, but where could I find the Maven library for Java?
Thanks.

**Comment by ansgarm** [comment]
Hi @mirsilstan!
Do you still have the AWS provider in your `cdktf.json`? If yes, that could cause that – you don't need it there if you use a prebuilt provider :)
