### ISSUE TITLE
Exported APIs cannot use un-exported type "@pahud/cdktf-aws-eks.EKS.EksCluster"

### ISSUE THREAD

**Issue by pahud** [hashicorp/cdktf-provider-aws#465]
Hi  @skorfmann 

I ran into this error when I upgrade cdktf 0.6.0 to 0.7.0 from this  https://github.com/pahud/cdktf-aws-eks/pull/61

<img width="1783" alt="圖片" src="https://user-images.githubusercontent.com/278432/138653293-0f021b79-2d3d-4447-8b45-fa5d9ca94207.png">

The complete CI log https://github.com/pahud/cdktf-aws-eks/runs/3993893529?check_suite_focus=true

Looks like the `EksCluster` is an exported class but somehow it complained not an exported class:
https://github.com/hashicorp/cdktf-provider-aws/blob/2c441c164977d7124602468bc5232dee7e03e8a9/src/EKS.ts#L659

Do you have any idea about this error?

**Comment by ansgarm** [comment]
Hi @pahud! I created a PR to upgrade to `v0.8.1`: https://github.com/pahud/cdktf-aws-eks/pull/63

Please have a look :)

**Comment by DanielMSchmidt** [comment]
Closing this, seems like it got fixed :)
